package org.ssm.pojo;

import java.io.Serializable;
import java.util.Date;

public class Employees implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.emp_no
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private Integer empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.birth_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.first_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.last_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.gender
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hire_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.brith_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private Date brithDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.firest_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private String firestName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.emp_no
     *
     * @return the value of employees.emp_no
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.emp_no
     *
     * @param empNo the value for employees.emp_no
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.birth_date
     *
     * @return the value of employees.birth_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.birth_date
     *
     * @param birthDate the value for employees.birth_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.first_name
     *
     * @return the value of employees.first_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.first_name
     *
     * @param firstName the value for employees.first_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.last_name
     *
     * @return the value of employees.last_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.last_name
     *
     * @param lastName the value for employees.last_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.gender
     *
     * @return the value of employees.gender
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.gender
     *
     * @param gender the value for employees.gender
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.hire_date
     *
     * @return the value of employees.hire_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.hire_date
     *
     * @param hireDate the value for employees.hire_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.brith_date
     *
     * @return the value of employees.brith_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public Date getBrithDate() {
        return brithDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.brith_date
     *
     * @param brithDate the value for employees.brith_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setBrithDate(Date brithDate) {
        this.brithDate = brithDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.firest_name
     *
     * @return the value of employees.firest_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public String getFirestName() {
        return firestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.firest_name
     *
     * @param firestName the value for employees.firest_name
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setFirestName(String firestName) {
        this.firestName = firestName == null ? null : firestName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Employees other = (Employees) that;
        return (this.getEmpNo() == null ? other.getEmpNo() == null : this.getEmpNo().equals(other.getEmpNo()))
            && (this.getBirthDate() == null ? other.getBirthDate() == null : this.getBirthDate().equals(other.getBirthDate()))
            && (this.getFirstName() == null ? other.getFirstName() == null : this.getFirstName().equals(other.getFirstName()))
            && (this.getLastName() == null ? other.getLastName() == null : this.getLastName().equals(other.getLastName()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getHireDate() == null ? other.getHireDate() == null : this.getHireDate().equals(other.getHireDate()))
            && (this.getBrithDate() == null ? other.getBrithDate() == null : this.getBrithDate().equals(other.getBrithDate()))
            && (this.getFirestName() == null ? other.getFirestName() == null : this.getFirestName().equals(other.getFirestName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmpNo() == null) ? 0 : getEmpNo().hashCode());
        result = prime * result + ((getBirthDate() == null) ? 0 : getBirthDate().hashCode());
        result = prime * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        result = prime * result + ((getLastName() == null) ? 0 : getLastName().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getHireDate() == null) ? 0 : getHireDate().hashCode());
        result = prime * result + ((getBrithDate() == null) ? 0 : getBrithDate().hashCode());
        result = prime * result + ((getFirestName() == null) ? 0 : getFirestName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empNo=").append(empNo);
        sb.append(", birthDate=").append(birthDate);
        sb.append(", firstName=").append(firstName);
        sb.append(", lastName=").append(lastName);
        sb.append(", gender=").append(gender);
        sb.append(", hireDate=").append(hireDate);
        sb.append(", brithDate=").append(brithDate);
        sb.append(", firestName=").append(firestName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}