package org.ssm.pojo;

import java.io.Serializable;
import java.util.Date;

public class Salaries extends SalariesKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.salary
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.to_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private Date toDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.salary
     *
     * @return the value of salaries.salary
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.salary
     *
     * @param salary the value for salaries.salary
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.to_date
     *
     * @return the value of salaries.to_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.to_date
     *
     * @param toDate the value for salaries.to_date
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Salaries other = (Salaries) that;
        return (this.getEmpNo() == null ? other.getEmpNo() == null : this.getEmpNo().equals(other.getEmpNo()))
            && (this.getFromDate() == null ? other.getFromDate() == null : this.getFromDate().equals(other.getFromDate()))
            && (this.getSalary() == null ? other.getSalary() == null : this.getSalary().equals(other.getSalary()))
            && (this.getToDate() == null ? other.getToDate() == null : this.getToDate().equals(other.getToDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmpNo() == null) ? 0 : getEmpNo().hashCode());
        result = prime * result + ((getFromDate() == null) ? 0 : getFromDate().hashCode());
        result = prime * result + ((getSalary() == null) ? 0 : getSalary().hashCode());
        result = prime * result + ((getToDate() == null) ? 0 : getToDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", salary=").append(salary);
        sb.append(", toDate=").append(toDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}