package org.ssm.dao;

import org.apache.ibatis.annotations.Mapper;
import org.ssm.pojo.Departments;

@Mapper
public interface IDepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int deleteByPrimaryKey(String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insert(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insertSelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    Departments selectByPrimaryKey(String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKeySelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKey(Departments record);
}