package org.ssm.dao;

import org.apache.ibatis.annotations.Mapper;
import org.ssm.pojo.DeptManager;
import org.ssm.pojo.DeptManagerKey;

@Mapper
public interface IDeptManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int deleteByPrimaryKey(DeptManagerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insert(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insertSelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    DeptManager selectByPrimaryKey(DeptManagerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKeySelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKey(DeptManager record);
}