package org.ssm.dao;

import org.apache.ibatis.annotations.Mapper;
import org.ssm.pojo.DeptEmp;
import org.ssm.pojo.DeptEmpKey;

@Mapper
public interface IDeptEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int deleteByPrimaryKey(DeptEmpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insert(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insertSelective(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    DeptEmp selectByPrimaryKey(DeptEmpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKeySelective(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKey(DeptEmp record);
}