package org.ssm.dao;

import org.apache.ibatis.annotations.Mapper;
import org.ssm.pojo.Employees;

@Mapper
public interface IEmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int deleteByPrimaryKey(Integer empNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insert(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insertSelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    Employees selectByPrimaryKey(Integer empNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKeySelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKey(Employees record);
}