package org.ssm.dao;

import org.apache.ibatis.annotations.Mapper;
import org.ssm.pojo.Salaries;
import org.ssm.pojo.SalariesKey;

@Mapper
public interface ISalariesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int deleteByPrimaryKey(SalariesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insert(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int insertSelective(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    Salaries selectByPrimaryKey(SalariesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKeySelective(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Mon Oct 28 11:00:15 CST 2019
     */
    int updateByPrimaryKey(Salaries record);
}